version: '3'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - PORT=8080
      - WEATHERAPI_KEY=${WEATHERAPI_KEY}
    restart: unless-stopped